# This file is autogenerated by the command `make fix-copies`, do not edit.
from ..utils import DummyObject, requires_backends


class DPMSolverSDEScheduler(metaclass=DummyObject):
    _backends = ["paddle", "paddlesde"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["paddle", "paddlesde"])

    @classmethod
    def from_config(cls, *args, **kwargs):
        requires_backends(cls, ["paddle", "paddlesde"])

    @classmethod
    def from_pretrained(cls, *args, **kwargs):
        requires_backends(cls, ["paddle", "paddlesde"])