# Copyright (c) 2024 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

colors_dict = {
    "红色": "Red",
    "橙色": "Orange",
    "黄色": "Yellow",
    "绿色": "Green",
    "蓝色": "Blue",
    "靛蓝色_1": "Indigo",
    "紫罗兰色": "Violet",
    "紫色": "Purple",
    "粉色": "Pink",
    "棕色": "Brown",
    "白色": "White",
    "黑色": "Black",
    "灰色": "Gray",
    "银色": "Silver",
    "金色": "Gold",
    "天蓝色": "Sky blue",
    "海军蓝": "Navy blue",
    "绿松石色": "Turquoise",
    "鲜绿色": "Lime green",
    "橄榄绿色": "Olive green",
    "珊瑚色": "Coral",
    "米色": "Beige",
    "灰褐色": "Taupe",
    "品红色": "Magenta",
    "栗色": "Maroon",
    "薰衣草色": "Lavender",
    "桃色": "Peach",
    "芥末色": "Mustard",
    "青色": "Teal",
    "猩红色_1": "Scarlet",
    "玫瑰红": "Rose",
    "桃红": "Peach Pink",
    "浅粉": "Baby Pink",
    "粉红": "Pinkish",
    "淡紫": "Lilac",
    "深紫": "Plum",
    "浅蓝": "Light Blue",
    "钴蓝": "Cobalt Blue",
    "水蓝": "Aqua Blue",
    "群青": "Ultramarine",
    "翠绿": "Emerald Green",
    "橄榄绿": "Olive",
    "古铜色_1": "Bronze",
    "琥珀色": "Amber",
    "酒红色": "Burgundy",
    "珊瑚粉": "Coral Pink",
    "肉粉色": "Flesh Pink",
    "米灰色": "Misty Gray",
    "米白": "Off-White",
    "米黄": "Beige Yellow",
    "香槟金": "Champagne Gold",
    "玫瑰金": "Rose Gold",
    "奶油色": "Cream",
    "淡金色": "Pale Gold",
    "浅黄色_1": "Pale Yellow",
    "柠檬黄": "Lemon Yellow",
    "浅绿色": "Light Green",
    "薄荷绿": "Mint Green",
    "荧光绿": "Neon Green",
    "翡翠绿_1": "Jade Green",
    "孔雀蓝": "Peacock Blue",
    "霓虹蓝": "Neon Blue",
    "樱桃红": "Cherry Red",
    "石榴红": "Pomegranate Red",
    "樱桃粉": "Cherry Blossom Pink",
    "橙红色": "Orange Red",
    "橙黄色": "Orange Yellow",
    "赭石色": "Ochre",
    "朱红色": "Vermilion",
    "砖红色": "Brick Red",
    "玫瑰棕": "Rose Brown",
    "奶茶色": "Milk Tea",
    "珍珠白": "Pearl White",
    "奶油白": "Creamy White",
    "胭脂红": "Carmine",
    "海棠红": "Begonia Red",
    "丁香紫": "Lilac Purple",
    "翡翠绿_2": "Jade",
    "宝石蓝": "Sapphire Blue",
    "矢车菊蓝": "Cornflower Blue",
    "宝石红": "Ruby Red",
    "猩红色_2": "Scarlet Red",
    "琥珀橙": "Amber Orange",
    "海棠色": "Begonia Color",
    "牡丹红": "Peony Red",
    "玫瑰紫": "Rose Violet",
    "薰衣草紫_1": "Lavender Purple",
    "马卡龙蓝": "Macaron Blue",
    "马卡龙粉": "Macaron Pink",
    "靛蓝色_2": "Indigo Blue",
    "群青色": "Ultramarine Blue",
    "古铜色_2": "Bronze Tone",
    "杏色": "Apricot",
    "秋香色": "Autumn Mellow",
    "黛色": "Indigo Black",
    "藤黄色": "Rattan Yellow",
    "茶色": "Tea Color",
    "豆沙色": "Bean Paste Color",
    "青绿色": "Turquoise Green",
    "翠绿色": "Emerald Green",
    "嫩绿色_1": "Light Green",
    "墨绿色": "Dark Green",
    "深绿色": "Deep Green",
    "青蓝色": "Cyan Blue",
    "蔚蓝色": "Azure Blue",
    "海蓝色": "Sea Blue",
    "深蓝色": "Dark Blue",
    "藏青色": "Navy Blue",
    "苍绿色": "Pale Green",
    "灰蓝色": "Grayish Blue",
    "粉蓝色": "Powder Blue",
    "棕红色": "Brownish Red",
    "砖红色": "Brick Red",
    "土黄色": "Earthy Yellow",
    "浅黄色_2": "Light Yellow",
    "米黄色": "Beige Yellow",
    "柠檬黄": "Lemon Yellow",
    "金黄色": "Golden Yellow",
    "杏黄色": "Apricot Yellow",
    "橄榄黄": "Olive Yellow",
    "玫瑰金": "Rose Gold",
    "香槟金": "Champagne Gold",
    "沙金色": "Sandy Gold",
    "古铜金": "Bronze Gold",
    "青铜色": "Bronze Color",
    "赤金色": "Copper Gold",
    "银白色": "Silver White",
    "银灰色": "Silver Gray",
    "铅灰色": "Leaden Gray",
    "炭灰色": "Charcoal Gray",
    "紫灰色": "Purple Gray",
    "苍白色": "Pale White",
    "米白色": "Off-White",
    "乳白色": "Creamy White",
    "象牙白": "Ivory White",
    "雪白色": "Snow White",
    "珍珠白": "Pearl White",
    "粉红色": "Pink",
    "浅粉色": "Light Pink",
    "桃粉色": "Peach Pink",
    "玫瑰粉": "Rose Pink",
    "淡紫色": "Lilac",
    "薰衣草紫_2": "Lavender",
    "天空蓝": "Sky Blue",
    "淡蓝色": "Light Blue",
    "薄荷绿": "Mint Green",
    "嫩绿色_2": "Baby Green",
    "柠檬黄": "Lemon Yellow",
    "明亮黄": "Bright Yellow",
    "鲜亮黄": "Vivid Yellow",
    "阳光黄": "Sunshine Yellow",
    "金黄": "Golden Yellow",
    "草莓红": "Strawberry Red",
    "珊瑚粉": "Coral Pink",
    "樱桃红": "Cherry Red",
    "奶油白": "Creamy White",
    "珍珠白": "Pearl White",
    "糖果色": "Candy Colors",
    "彩虹色": "Rainbow Colors",
}
