# Copyright (c) 2024 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

fashion_dict = {
    "吊带连衣裙": "Slip Skirt",
    "雪纺衬衫": "Chiffon Shirt",
    "牛仔外套": "Denim Jacket",
    "运动卫衣": "Sports Hoodie",
    "A字裙": "A-line Skirt",
    "荷叶边半身裙": "Ruffle Skirt",
    "蕾丝吊带背心": "Lace Camisole",
    "蕾丝连衣裙": "Lace Skirt",
    "高腰短裤": "High-waisted Shorts",
    "印花T恤": "Printed T-shirt",
    "拼色连衣裙": "Color-blocked Skirt",
    "蕾丝边短裤": "Lace Trim Shorts Skirt",
    "蝴蝶结连衣裙": "Bowknot Skirt",
    "蕾丝发带": "Lace Headband",
    "针织开衫": "Cardigan",
    "荷叶边短裙": "Ruffle Skirt",
    "泡泡袖上衣": "Puff Sleeve Top",
    "露肩上衣": "Off-the-shoulder Top",
    "流苏短裙": "Fringe Skirt",
    "波点连衣裙": "Polka Dot Skirt",
    "波点短裙": "Polka Dot Skirt",
    "荷叶边上衣": "Ruffle Top",
    "蝴蝶结发饰": "Bowknot Hair Accessory",
    "蕾丝手套": "Lace Gloves",
    "碎花连衣裙": "Floral Print Skirt",
    "牛仔短裤": "Denim Shorts",
    "甜美蕾丝吊带": "Sweet Lace Camisole Skirt",
    "蕾丝边袜": "Lace Trim Socks",
    "蝴蝶结平底鞋": "Bowknot Flats",
    "裹身裙_1": "Wrap Skirt",
    "鱼尾裙": "Fishtail Skirt",
    "蕾丝裙": "Lace Skirt",
    "高腰裙": "High-Waisted Skirt",
    "蛋糕裙": "Tiered Skirt",
    "不对称裙": "Asymmetric Skirt",
    "旗袍": "Cheongsam",
    "汉服": "Hanfu Skirt",
    "紧身裙": "Pencil Skirt",
    "迷你裙": "Mini Skirt",
    "半身裙": "Skirt",
    "A字裙": "A-line Skirt",
    "百褶裙": "Pleated Skirt",
    "印花裙": "Printed Skirt",
    "蕾丝边裙": "Lace Trim Skirt",
    "波点裙": "Polka Dot Skirt",
    "吊带裙": "Slip Skirt (as a skirt alternative)",
    "荷叶边裙": "Ruffle Skirt",
    "雪纺裙": "Chiffon Skirt",
    "绸缎裙": "Satin Skirt",
    "丝绒裙": "Velvet Skirt",
    "蕾丝拼接裙": "Lace Patchwork Skirt",
    "蓬蓬裙": "Tutu Skirt",
    "裹身裙_2": "Wrap Skirt",
    "鱼尾裙": "Fishtail Skirt",
    "开叉裙": "Split Skirt",
    "蕾丝裙": "Lace Skirt",
    "高腰裙": "High-Waisted Skirt",
    "蛋糕裙": "Tiered Skirt",
    "不对称裙": "Asymmetric Skirt",
    "旗袍": "Cheongsam",
    "汉服裙": "Hanfu Skirt",
    "紧身裙": "Pencil Skirt",
    "迷你裙": "Mini Skirt",
    "半身裙": "Skirt",
    "A字裙": "A-line Skirt",
    "百褶裙": "Pleated Skirt",
    "印花裙": "Printed Skirt",
    "蕾丝边裙": "Lace Trim Skirt",
    "波点裙": "Polka Dot Skirt",
    "吊带裙": "Slip Skirt (as a skirt alternative)",
    "荷叶边裙": "Ruffle Skirt",
    "雪纺裙": "Chiffon Skirt",
    "绸缎裙": "Satin Skirt",
    "丝绒裙": "Velvet Skirt",
    "蕾丝拼接裙": "Lace Patchwork Skirt",
    "蓬蓬裙": "Tutu Skirt",
    "直筒裙": "Straight Skirt",
    "斜裁裙": "Bias Cut Skirt",
    "高腰A字裙": "High-Waisted A-line Skirt",
    "褶皱裙": "Ruffled Skirt",
    "针织裙": "Knitted Skirt",
    "流苏裙": "Fringe Skirt",
    "金属装饰裙": "Metallic Skirt",
    "蕾丝镂空裙": "Lace Cut-out Skirt",
    "拼接色块裙": "Block Color Skirt",
    "花苞裙": "Bloom Skirt",
    "蕾丝吊带裙": "Lace Camisole Skirt (as a skirt alternative)",
    "流苏装饰裙": "Fringe Trimmed Skirt",
    "网纱裙": "Tulle Skirt",
    "挂脖裙": "Halter Skirt",
    "荷叶边蛋糕裙": "Ruffled Tiered Skirt",
    "睡衣_1": "Sleepwear Skirt",
    "睡衣_2": "Intimate Wear Skirt",
}
