pretrained_base_model_path: "runwayml/stable-diffusion-v1-5"
pretrained_vae_path: "stabilityai/sd-vae-ft-mse"
image_encoder_path: "lambdalabs/sd-image-variations-diffusers/image_encoder"

denoising_unet_config_path: "./pretrained_weights/tsaiyue/AnimateAnyone_PD/config.json"
denoising_unet_path: "./pretrained_weights/tsaiyue/AnimateAnyone_PD/denoising_unet.pdparams"
reference_unet_path: "./pretrained_weights/tsaiyue/AnimateAnyone_PD/reference_unet.pdparams"
pose_guider_path: "./pretrained_weights/tsaiyue/AnimateAnyone_PD/pose_guider.pdparams"

motion_module_path: "./pretrained_weights/tsaiyue/AnimateAnyone_PD/motion_module_stage2.pdparams"

inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'

test_cases:
  "./configs/inference/ref_images/girl_in_black.png":
    - "./configs/inference/pose_videos/girl_in_black.mp4"
  "./configs/inference/ref_images/sora_woman.png":
    - "./configs/inference/pose_videos/fashion1_kps.mp4"
  "./configs/inference/ref_images/iron_man.png":
    - "./configs/inference/pose_videos/anyone-video-1_kps.mp4"
  "./configs/inference/ref_images/younglady.png":
    - "./configs/inference/pose_videos/anyone-video-2_kps.mp4"
 