[metadata]
name = qdiff
version = 0.1.0
author = Your Name
author_email = your.email@example.com
description = A PaddlePaddle quantization utils library
long_description = ''
long_description_content_type = text/markdown
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.8
install_requires =
    numpy

[options.package_data]
* = *.yaml, *.json  # 如果你有额外的资源文件
